### ISSUE TITLE
Thunder_Viewer.exe 

### ISSUE THREAD

**Issue by Userpc1010** [PowerBroker2/Thunder_Viewer#3]
> 1.     Download the latest release
> 2.     Extract the Thunder_Viewer.zip where you want
> 3.     Open the extracted file
> 4.     Double click Thunder_Viewer.exe

When I open the extracted file: https://b.radikal.ru/b12/2003/86/9910f0aed397.png
Of course this is fixable and possible download the source code but i think need fixed it.

**Comment by PowerBroker2** [comment]
Image:
![image](https://b.radikal.ru/b12/2003/86/9910f0aed397.png)

**Comment by PowerBroker2** [comment]
You're right, you can work around it by running the Python files, but I should get the .exe fixed. Can you translate the Russian lines to English?

Note that I've had others launch the .exe (they didn't even have Python installed) and it did work for them.

**Comment by Userpc1010** [comment]
There are not dynamic libraries ssl.py and pyi_rht_certifi.py.

DLL load failed: file not found.

**Comment by Userpc1010** [comment]
By the way, a great project! But there are doubts that the autopilot, after testing in the simulator, will be able to fly, because the response time of the servos and their gear ratio to the rudder in WarTunder cannot be simulated. In addition, BNO 055 cannot always correctly calculate orientation, unlike virtual sensors in the game.

I am also doing a similar autopilot project but till not able to successful fly tests. I testing the fly stabilization algorithm in the kerbal space program game whith kOS mod but these settings are not suitable. I hope you succeed the first time.

**Comment by PowerBroker2** [comment]
Yeah, I've been able to do some successful Arduino autopilot simulations with War Thunder for my personal Arduino RC research plane. I'm guessing you came here from my FliteTest forum thread?

**Comment by PowerBroker2** [comment]
I'll take a look and see if I can get ssl.py and pyi_rht_certifi.py explicitly included in the .exe. Do you have Python installed and know how to use it?

Also, what are you developing an autopilot for?

**Comment by Userpc1010** [comment]
Yes, from a forum or youtube channel.

**Comment by Userpc1010** [comment]
No, Python is not installed, this may be a problem, usually I use only C / C ++ but I think I can figure it out.

Autopilot developing, just for fun.

**Comment by PowerBroker2** [comment]
I updated the latest release's zip file. I tried to manually add ssl.py, but I could not figure out what the whole pyi_rht_certifi.py thing is about. I don't even have that file on my computer. Maybe it's a Windows 7 issue?

**Comment by Userpc1010** [comment]
Perhaps the problem is in the system, it is already a lot of time 1:30 in Moscow, tomorrow I will try to find and add these files. I also installed IDEL Anaconda 3 and now download sources as well.

**Comment by Userpc1010** [comment]
After launch run.bat:

<img src="https://c.radikal.ru/c11/2003/36/34b3063e1d43.jpg" width="480" height="240"/>

And I modified setup.bat:

1. pip install paho-mqtt
2.  pip install pySerialTransfer
3.  pip install WarThunder
4.  pip install ntplib
5.  pip install imagehash
6.  pip install Pillow
7.  pip install pyserial
8.  pip install PyQt5
9.  pip install requests
PAUSE

**Comment by Userpc1010** [comment]
After launch setup with anaconda pip:

<img src="https://b.radikal.ru/b40/2003/7e/0b119a7ac703.jpg" />

If manual add folder War Thunder in lib anaconda and start run.bat i have error how in last comment.

**Comment by PowerBroker2** [comment]
Seems that your Python/pip install is either incomplete and/or broken. The printouts are saying pip can't install any new packages because of an SSL error due to the SSL module not being available on your machine. Are you sure you installed Anaconda and pip correctly?

**Comment by Userpc1010** [comment]
I used the Anaconda3-2020.02-Windows-x86_64 auto-installer, I think it installs everything correctly.
As I already write, if use Python pip.exe, everything works fine in setup.bat. 

<img src="https://a.radikal.ru/a41/2003/42/1b7046fa5788.jpg" />

**Comment by Userpc1010** [comment]
Ok, error with SSL module in anaconda[ is fixed](https://github.com/conda/conda/issues/8273) need copy:

> 
>  "C:\ProgramData\Anaconda3\Library\bin\libcrypto-1_1-x64.dll" to "C:\ProgramData\Anaconda3\DLLs\libcrypto-1_1-x64.dll" 
> 
> and
>
> "C:\ProgramData\Anaconda3\Library\bin\libssl-1_1-x64.dll" to "C:\ProgramData\Anaconda3\DLLs\libssl-1_1-x64.dll"

<img src="https://b.radikal.ru/b26/2003/3a/e781ba8862d9.jpg" />

But the error with the socket remained:


> 
> 
> After launch run.bat:
> 
> <img alt="" width="480" height="240" src="https://camo.githubusercontent.com/421e5a8344f195e9e24eb708bb11ceac4dc1508f/68747470733a2f2f632e726164696b616c2e72752f6331312f323030332f33362f3334623330363365316434332e6a7067">
> 
> And I modified setup.bat:
> 
>     1. pip install paho-mqtt
> 
>     2. pip install pySerialTransfer
> 
>     3. pip install WarThunder
> 
>     4. pip install ntplib
> 
>     5. pip install imagehash
> 
>     6. pip install Pillow
> 
>     7. pip install pyserial
> 
>     8. pip install PyQt5
> 
>     9. pip install requests
>        PAUSE

**Comment by PowerBroker2** [comment]
Can you open up Spyder.exe (included in Anaconda) and enter the following in the IPython workspace:

```Python
import socket    
hostname = socket.gethostname()    
IPAddr = socket.gethostbyname(hostname)    
print("Your Computer Name is:" + hostname)    
print("Your Computer IP Address is:" + IPAddr)  
```

Let me know what it says as an output.

**Comment by Userpc1010** [comment]
Result:
<img src="https://c.radikal.ru/c20/2003/2d/cf96d0d26b81.jpg" />

**Comment by Userpc1010** [comment]
Everything is like on the command line, I have not yet found a solution, if I find out I will inform.

**Comment by PowerBroker2** [comment]
What does it say when you run:

```Python
import socket
hostname = socket.gethostname()
print("Your Computer Name is: " + hostname)
```

**Comment by Userpc1010** [comment]
runfile('C:/Users/Admin/.spyder-py3/temp.py', wdir='C:/Users/Admin/.spyder-py3')
Your Computer Name is: Admin-ПК
Fine

**Comment by Userpc1010** [comment]
```
import socket    
 hostname = socket.gethostname()    
 #IPAddr = socket.gethostbyname(hostname.strip() )  
 print (socket.getaddrinfo('10.43.159.127', 9092))
 print("Your Computer Name is:" + hostname)    
 #print("Your Computer IP Address is:" + IPAddr)
```
> [(<AddressFamily.AF_INET: 2>, 0, 0, '', ('10.43.159.127', 9092))]
> Your Computer Name is:Admin-ПК

**Comment by PowerBroker2** [comment]
The socket package might be having a difficult time with special characters like '-' and 'П'. I can't help too much with that, though.

**Comment by PowerBroker2** [comment]
What you're probably better off writing a program yourself that grabs War Thunder data and sends it to your Arduino. You can use the source code of the [WarThunder Python package](https://github.com/PowerBroker2/WarThunder/tree/master/WarThunder) to get an idea on how to do it.

**Comment by Userpc1010** [comment]
If change the host name is there a chance?

**Comment by PowerBroker2** [comment]
Only testing can tell

**Comment by Userpc1010** [comment]
There are results:

<img src="https://c.radikal.ru/c23/2003/76/df173923f5a7.jpg" />

**Comment by Userpc1010** [comment]
I think can try to run without anaconda

**Comment by PowerBroker2** [comment]
How did you get it to work? Change the host name?

**Comment by Userpc1010** [comment]
Yes, I changed the host name to “Admin”, now I deleted the anaconda, it also works without it.
