### ISSUE TITLE
Thunder Viewer

### ISSUE THREAD

**Issue by Sekupas** [PowerBroker2/Thunder_Viewer#8]
after start the .exe file, the command prompt say me:
![image](https://user-images.githubusercontent.com/64388676/190373994-d130d765-7316-4f2f-ae6a-b29a5dbc754b.png)
where I was wrong

**Comment by Sekupas** [comment]
and in sketch on arduino that say me "'Serial2' was not declared in this scope"
![image](https://user-images.githubusercontent.com/64388676/190374462-b7949615-5b32-4620-b801-4a8c0447feda.png)

**Comment by PowerBroker2** [comment]
My guess is that your issue is related to this one: [link](https://github.com/PowerBroker2/Thunder_Viewer/issues/3#issuecomment-605686988)

**Comment by Sekupas** [comment]
> My guess is that your issue is related to this one: [link](https://github.com/PowerBroker2/Thunder_Viewer/issues/3#issuecomment-605686988)

What u can say about the problem with arduino sketch?

**Comment by Sekupas** [comment]
i fix the first error, i start the exe file with anaconda prompt
